using System.Net.Http.Headers;
using System.Text;
using MongoDB.Driver;
using Newtonsoft.Json;
using ShoppingPlatform.DTOs;
using ShoppingPlatform.Models;
using ShoppingPlatform.Repositories;

namespace ShoppingPlatform.Services
{
    public class DelhiveryDeliveryService : IDeliveryService
    {
        private readonly HttpClient _httpClient;
        private readonly ISecretsRepository _secretsRepository;

        private string? _apiToken;
        private string? _pickupLocation;
        private readonly ILogger<DelhiveryDeliveryService> _logger;
        private readonly IMongoCollection<Counter> _counters;

        public DelhiveryDeliveryService(
            HttpClient httpClient,
            ISecretsRepository secretsRepository,
            ILogger<DelhiveryDeliveryService> logger, IMongoDatabase db)
        {
            _httpClient = httpClient;
            _secretsRepository = secretsRepository;
            _logger = logger;
            _counters = db.GetCollection<Counter>("counters");

        }

        // 🔐 Load secrets once (lazy + cached)
        private async Task EnsureSecretsLoadedAsync()
        {
            if (!string.IsNullOrEmpty(_apiToken))
            {
                _logger.LogDebug("Delhivery secrets already loaded (cached)");
                return;
            }

            _logger.LogInformation("Loading Delhivery secrets from database");

            var secrets = await _secretsRepository.GetSecretsByAddedForAsync("DELHIVERY");

            if (secrets == null)
            {
                _logger.LogError("Delhivery secrets document not found");
                throw new Exception("Delhivery secrets not found");
            }

            if (string.IsNullOrEmpty(secrets.DelhiveryApiToken))
            {
                _logger.LogError("Delhivery API token missing in secrets");
                throw new Exception("Delhivery API token not configured");
            }

            if (string.IsNullOrEmpty(secrets.DelhiveryPickupLocation))
            {
                _logger.LogError("Delhivery pickup location missing in secrets");
                throw new Exception("Delhivery pickup location not configured");
            }

            _apiToken = secrets.DelhiveryApiToken;
            _pickupLocation = secrets.DelhiveryPickupLocation;

            _httpClient.DefaultRequestHeaders.Authorization =
                new AuthenticationHeaderValue("Token", _apiToken);

            _logger.LogInformation(
                "Delhivery secrets loaded successfully. PickupLocation={PickupLocation}",
                _pickupLocation
            );
        }


        // 🌍 INTERNATIONAL
        public async Task<string> CreateInternationalShipmentAsync(
            InternationalDeliveryRequest request)
        {
            await EnsureSecretsLoadedAsync();

            // INTERNAL reference only (NOT AWB)
            var internalShipmentId = await GenerateInternalShipmentIdAsync();
            request.OrderId = internalShipmentId;

            var formData = new Dictionary<string, string>
    {
        { "format", "json" },

        // Your reference
        { "shipment_order_id", request.OrderId },

        // Destination
        { "destination_country", request.CountryCode }, // US, AE, SG

        // Consignee (FLAT)
        { "consignee_name", request.Name },
        { "consignee_address", request.Address },
        { "consignee_phone", request.DropPhone },

        // Shipment
        { "commodity", request.Commodity },              // Apparel, Electronics
        { "shipment_weight", request.Weight.ToString() },// > 0.1
        { "shipment_value", request.Value.ToString() },
        { "currency", request.Currency }                 // USD, AED
    };

            var responseBody = await PostFormAsync(
                "/api/international/create",
                formData
            );

            var parsed = JsonConvert.DeserializeObject<dynamic>(responseBody);

            if (parsed?.success != true)
                throw new Exception($"INTL shipment failed: {responseBody}");

            // ✅ REAL AWB GENERATED BY DELHIVERY
            var delhiveryAwb = (string)parsed.awb;


            return delhiveryAwb;
        }
        public async Task<string> CreateDomesticShipmentAsync(DomesticShipmentRequest request)
        {
            await EnsureSecretsLoadedAsync();

            var payload = new
            {
                pickup_location = new
                {
                    name = _pickupLocation // must exist in Delhivery panel
                },
                shipments = new[]
                {
            new
            {
                order = request.OrderId,          // YOUR internal order id
                weight = request.Weight.ToString(),
                pin = request.DropPincode,
                products_desc = "Clothes",
                add = request.DropAddress,
                state = request.DropState,
                city = request.DropCity,
                phone = request.DropPhone,
                payment_mode = request.IsCod ? "COD" : "Prepaid",
                name = request.DropName,
                total_amount = request.Amount,
                country = "India"
            }
        }
            };

            var formData = new Dictionary<string, string>
    {
        { "format", "json" },
        { "data", JsonConvert.SerializeObject(payload) }
    };

            var responseBody = await PostFormAsync("/api/cmu/create.json", formData);

            var parsed = JsonConvert.DeserializeObject<dynamic>(responseBody);

            if (parsed?.success != true)
                throw new Exception($"Domestic shipment failed: {responseBody}");

            // ✅ THIS is the ONLY valid waybill
            return parsed.packages[0].waybill;
        }


        // 🇮🇳 DOMESTIC (FORWARD + REVERSE)
        //    public async Task<string> CreateDomesticShipmentAsync(DomesticShipmentRequest request)
        //    {
        //        await EnsureSecretsLoadedAsync();

        //        var shipment = new
        //        {
        //            order = request.OrderId,
        //            is_reverse = request.IsReverse,

        //            name = request.PickupName,
        //            phone = request.PickupPhone,
        //            add = request.PickupAddress,
        //            pin = request.PickupPincode,

        //            return_name = request.DropName,
        //            return_phone = request.DropPhone,
        //            return_add = request.DropAddress,
        //            return_pin = request.DropPincode,

        //            payment_mode = request.IsCod ? "COD" : "Prepaid",
        //            cod_amount = request.IsCod ? request.CodAmount : 0,

        //            weight = request.Weight
        //        };

        //        var formData = new Dictionary<string, string>
        //{
        //    { "format", "json" }, // 🔥 THIS IS WHAT DELHIVERY READS
        //    { "shipments", JsonConvert.SerializeObject(new[] { shipment }) },
        //    { "pickup_location", JsonConvert.SerializeObject(new { name = _pickupLocation }) }
        //};

        //        var responseBody = await PostFormAsync("/api/cmu/create.json", formData);

        //        var parsed = JsonConvert.DeserializeObject<dynamic>(responseBody);

        //        if (parsed?.success != true)
        //            throw new Exception($"Domestic shipment failed: {responseBody}");

        //        return parsed.packages[0].waybill;
        //    }

        // 📦 TRACKING

        public async Task<string> GenerateInternalShipmentIdAsync()
        {
            var filter = Builders<Counter>.Filter.Eq(x => x.CounterFor, "DOMESTIC_SHIPMENT");

            var update = Builders<Counter>.Update.Inc(x => x.Seq, 1);

            var options = new FindOneAndUpdateOptions<Counter>
            {
                IsUpsert = true,
                ReturnDocument = ReturnDocument.After
            };

            var counter = await _counters.FindOneAndUpdateAsync(
                filter,
                update,
                options
            );

            // Example: SHP-00000123
            return $"SHP-{counter.Seq:D8}";
        }

        public async Task<string> TrackShipmentAsync(string awb)
        {
            await EnsureSecretsLoadedAsync();

            var response = await _httpClient.GetAsync(
                $"https://track.delhivery.com/api/v1/packages/json/?waybill={awb}");

            response.EnsureSuccessStatusCode();
            return await response.Content.ReadAsStringAsync();
        }

        // ❌ CANCEL SHIPMENT
        public async Task CancelShipmentAsync(string awb)
        {
            await EnsureSecretsLoadedAsync();

            _logger.LogInformation("Cancelling shipment | AWB={Awb}", awb);

            var formData = new Dictionary<string, string>
    {
        { "waybill", awb },
        { "cancellation", "true" }
    };

            string url = "https://track.delhivery.com/api/p/edit";

            _logger.LogDebug(
                "Delhivery CANCEL FORM payload: {@Payload}",
                formData
            );

            var content = new FormUrlEncodedContent(formData);

            var response = await _httpClient.PostAsync(url, content);
            var responseBody = await response.Content.ReadAsStringAsync();

            _logger.LogDebug(
                "Delhivery CANCEL response | Status={Status} | Body={Body}",
                response.StatusCode,
                responseBody
            );

            if (!response.IsSuccessStatusCode)
                throw new Exception($"Cancel shipment failed: {responseBody}");
        }


        // 🔧 COMMON POST HANDLER
        private async Task<string> PostFormAsync(string url, Dictionary<string, string> formData)
        {
            string APIurl = "https://track.delhivery.com" + url;

            _logger.LogInformation("Calling Delhivery FORM API: {Url}", APIurl);
            _logger.LogDebug("Delhivery FORM Payload: {@Payload}", formData);

            var content = new FormUrlEncodedContent(formData);

            var response = await _httpClient.PostAsync(APIurl, content);
            var responseBody = await response.Content.ReadAsStringAsync();

            _logger.LogDebug(
                "Delhivery FORM Response | Status={Status} | Body={Body}",
                response.StatusCode,
                responseBody
            );

            if (!response.IsSuccessStatusCode)
                throw new Exception($"Delhivery API error: {responseBody}");

            return responseBody;
        }


        public async Task SchedulePickupAsync(string awb)
        {
            await EnsureSecretsLoadedAsync();

            _logger.LogInformation("Scheduling pickup for AWB={Awb}", awb);

            var formData = new Dictionary<string, string>
    {
        { "waybill", awb },
        { "pickup_date", DateTime.UtcNow.ToString("yyyy-MM-dd") }
    };

            _logger.LogDebug(
                "Delhivery PICKUP FORM payload: {@Payload}",
                formData
            );

            string url = "https://track.delhivery.com/api/p/pickup";

            var content = new FormUrlEncodedContent(formData);

            var response = await _httpClient.PostAsync(url, content);
            var responseBody = await response.Content.ReadAsStringAsync();

            _logger.LogDebug(
                "Delhivery PICKUP response | Status={Status} | Body={Body}",
                response.StatusCode,
                responseBody
            );

            if (!response.IsSuccessStatusCode)
                throw new Exception($"Pickup scheduling failed: {responseBody}");

            _logger.LogInformation(
                "Pickup scheduled successfully for AWB={Awb}",
                awb
            );
        }



    }
}
